# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "1.1.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/fcavani/afero"

[[constraint]]
  branch = "master"
  name = "github.com/fcavani/e"

[[constraint]]
  branch = "master"
  name = "github.com/fcavani/http"

[[constraint]]
  branch = "master"
  name = "github.com/fcavani/net"

[[constraint]]
  branch = "master"
  name = "github.com/fcavani/rand"

[[constraint]]
  branch = "master"
  name = "github.com/fcavani/slog"

[[constraint]]
  branch = "master"
  name = "github.com/fcavani/systemd"

[[constraint]]
  branch = "master"
  name = "github.com/fcavani/text"

[[constraint]]
  branch = "master"
  name = "github.com/fcavani/types"

[[constraint]]
  branch = "master"
  name = "github.com/fcavani/viperutil"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sony/gobreaker"
  version = "0.3.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/xordataexchange/crypt"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/fcavani/httprouter.v2"

[[constraint]]
  name = "gopkg.in/vmihailenco/msgpack.v2"
  version = "2.9.1"

[prune]
  go-tests = true
  unused-packages = true